# Generated by Django 3.2.5 on 2021-07-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phoneimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneImages',
            new_name='PhoneImage',
        ),
    ]
